apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-is
spec:
  params:
  - name: is-infra-directory
  - name: IMAGE
  - name: release-name
  - name: configurations
  steps:
  - name: setup-custom-resource
    image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/yq-zip
    workingDir: $(workspaces.input.path)
    script: |
      is_manifest_template=$(workspaces.input.path)/$(params.is-infra-directory)/IntegrationServer.yaml

      mkdir -p $(workspaces.input.path)/integration_server
      is_manifest_rendered=$(workspaces.input.path)/integration_server/IntegrationServer.yaml

      cp $is_manifest_template $is_manifest_rendered

      e=$(params.release-name) yq e -i '.metadata.name = env(e)' $is_manifest_rendered
      e=$(params.IMAGE) yq e -i '.spec.pod.containers.runtime.image = env(e)'  $is_manifest_rendered

      yq --version
      
      for configuration in $(params.configurations) ; do
        config=$configuration yq e -i '.spec.configurations = (.spec.configurations // []) + env(config)' $is_manifest_rendered
      done

  - name: deploy-integration-server
    image: quay.io/openshift/origin-cli:latest
    workingDir: $(workspaces.input.path)
    command: ["oc"]
    args: ["apply", "-f", "integration_server/IntegrationServer.yaml"]

  workspaces:
    - name: input
